apiVersion: v1
kind: Service
metadata:
  name: blog-project-service
spec:
  selector:
    app: blog-project
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30080
  type: NodePort