name: Test on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: django_db

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print PostgreSQL logs
      run: docker logs db

    - name: Wait for PostgreSQL to become ready
      run: |
        for i in {1..10}; do
          pg_isready -h db -U postgres && echo Success && exit 0
          echo -n .
          sleep 1
        done
        echo Failed waiting for Postgres && exit 1

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run migrations and tests
      run: |
        python blog_project/manage.py migrate
        python blog_project/manage.py test
